In [1]:
import numpy as np

# arange

In [28]:
arr1 = np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Nan

In [1]:
np.nan

nan

# random
> random.rand()

> random.randint()

> random.randn()

> random.standard_normal()

> random.normal()

> random.random_sample()

> random.choice()

> random.seed()

## random.rand()
- [0,1) 범위 균일한 분포에서 난수 matrix array 생성

In [18]:
np.random.rand(5)

array([0.58805677, 0.79863803, 0.77652506, 0.45803167, 0.96850277])

In [19]:
np.random.rand(2,3)

array([[0.15698316, 0.74477967, 0.62348111],
       [0.26068669, 0.55566336, 0.41985311]])

## random.randint()
- [최솟값, 최댓값) 범위의 균일 분포에서 임의의 정수 추출

In [23]:
# [0,2) 범위
np.random.randint(2, size = 5)

array([0, 1, 0, 0, 0])

In [21]:
np.random.randint(2, 4, size=5)

array([3, 2, 3, 3, 2])

In [22]:
np.random.randint(1, 5, size = (2,3))

array([[4, 4, 1],
       [3, 1, 3]])

## random.randn()
- 표준정규분포 (Standard normal distribution)로부터 샘플링된 난수를 반환

In [24]:
np.random.randn(5)

array([ 0.39118892, -1.40274623, -1.43578506, -0.313545  , -0.82098503])

In [25]:
np.random.randn(2,3)

array([[ 0.94192048, -3.71450768,  0.61576201],
       [ 0.31857288, -1.47915475,  2.4937028 ]])

In [26]:
sigma, mu = 2, 100

In [27]:
sigma * np.random.randn(5) + mu

array([ 99.72174132, 100.29731877, 100.74940295,  99.2055184 ,
        99.18905308])

## random.standard_normal()
- 표준정규분포 (Standard normal distribution)로부터 샘플링된 난수를 반환
- standard_normal() 함수는 randn() 함수와 비슷하지만, 튜플을 인자로 받는다는 점에서 차이가 있음.

> standard_ 여러 분포가 있음
- cauchy distribution
- exponential distribution
- gamma distribution
- t distribution
- normal distribution

In [29]:
np.random.standard_normal(3)

array([ 0.68492736, -0.51293005,  1.03442492])

In [30]:
np.random.standard_normal((2,3))

array([[0.13795641, 0.45293221, 0.54799778],
       [0.3221594 , 0.09805417, 0.10208448]])

In [ ]:
np.random.st

## random.normal()
- 정규 분포 (Normal distribution)로부터 샘플링된 난수를 반환
- 평균, 표준편차, 난수의 수

In [31]:
np.random.normal(0, 1, 2)

array([ 0.4214645 , -1.44794355])

In [32]:
np.random.normal(1.5, 1.5, 4)

array([1.25485356, 0.16972321, 2.19114902, 1.50390487])

In [33]:
np.random.normal(3.0, 2.0, (2,3))

array([[3.93983284, 1.74930351, 2.3416965 ],
       [4.72353553, 2.90148465, 1.01428231]])

## random.random_sample() 
- [0.0, 1.0) 범위에서 샘플링된 임의의 실수를 반환

In [36]:
np.random.random_sample()

0.05574514105255446

In [37]:
np.random.random_sample((5,2))

array([[0.23094777, 0.77620528],
       [0.26098017, 0.7368287 ],
       [0.17128325, 0.26827853],
       [0.33731538, 0.11104819],
       [0.32083254, 0.97292442]])

In [38]:
np.random.random_sample((3,2)) - 3

array([[-2.66654007, -2.47060178],
       [-2.64331277, -2.80271037],
       [-2.62681575, -2.7504196 ]])

## random.choice() 
- 주어진 1차원 어레이로부터 임의의 샘플을 생성.

In [39]:
# np.arnage(5)에서 3개의 샘플
np.random.choice(5,3)

array([0, 4, 3])

In [40]:
np.random.choice(10, (2,3))

array([[5, 4, 1],
       [4, 5, 0]])

## random.seed()
- 난수 생성에 필요한 시드를 설정.
- 시드 설정하면 코드를 실행할 때마다 동일한 난수 생성

In [41]:
np.random.seed(0)

In [42]:
np.random.rand(2,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

# min, max, sort
- min : 최솟값
- max : 최댓값
- sort : 작은 값 부터 반환

In [36]:
arr = np.array([1,2,3,4,5,6,7,8])

In [37]:
np.min(arr)

1

In [38]:
np.max(arr)

8

In [39]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# argmin, argmax, argsort
- argmin : 최솟값 위치 (인덱스)
- argmax : 최댓값 위치 (인덱스)
- argsort : 작은 값부터 위치 반환 (인덱스)

In [43]:
# index는 0부터 시작
np.argmin(arr)

0

In [41]:
np.argmax(arr)

7

In [42]:
np.argsort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

# where
- 조건문을 사용할 때

## basic
- np.where() - 인덱스 반환

In [44]:
# 인덱스 반환
np.where(arr<5)

(array([0, 1, 2, 3], dtype=int64),)

In [45]:
# 값 반환
arr[np.where(arr<5)]

array([1, 2, 3, 4])

## 조건문으로 사용 (값 변경)
- np.where(condition, T, F) 값 변경

In [46]:
# arr가 10보다 크면 10으로 나누고 아니면 그대로
np.where(arr>=5, arr*10, arr)

array([ 1,  2,  3,  4, 50, 60, 70, 80])

In [48]:
# 조건에 만족하는 갯수를 구할 수 있음
sum(np.where(arr >= 5, True, False))

4

# reshape
- 차원이 맞지 않는 걸 지정해주면 오류가 발생함

## 1차원 -> 2차원

In [2]:
a = np.arange(1,9)
b = np.reshape(a, (2,4))
c = np.reshape(a, (4,2))

print(a)
print('\n')
print(b)
print('\n')
print(c)

[1 2 3 4 5 6 7 8]


[[1 2 3 4]
 [5 6 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
# 이렇게도 가능
d = a.reshape(2,4)
print(d)

[[1 2 3 4]
 [5 6 7 8]]


## 1차원 -> 3차원

In [5]:
e = a.reshape(2,2,2)
e

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
e[0]

array([[1, 2],
       [3, 4]])

In [7]:
# 3차원에서 첫번째 행렬의 1행 2열 값 인덱싱
e[0][0,1]

2

## -1의 의미
> reshape(-1, 정수) or reshape(정수, -1)
- 변경된 배열의 ‘-1’ 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻
- 행(row)의 위치에 -1을 넣고 열의 값을 지정해주면 변환될 배열의 행의 수는 알아서 지정
- 마찬가지로 행(row)의 수를 지정해주면 열은 알아서 자동으로 재배열을 해주는 것
- -1만 들어가면 1차원 배열을 반환

In [10]:
x = np.arange(12)
y = x.reshape(3,4)

print(x)
print('\n')
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
x = np.arange(12)
y = x.reshape(-1,3)

print(x)
print('\n')
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
x = np.arange(12)
y = x.reshape(3,-1)

print(x)
print('\n')
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
x = np.arange(12)
y = x.reshape(-1)

print(x)
print('\n')
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[ 0  1  2  3  4  5  6  7  8  9 10 11]
